MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: './checkpoints/jx_vit_base_p16_224-80ecf9dd.pth'
#  PRETRAIN_PATH: './checkpoints/market_transformer_120.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('6')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [16, 16]
#  STRIDE_SIZE: [12, 12]
  # source pretrain
#  SOURCE_PRETRAIN: './checkpoints/market_transformer_80_1gpu.pth'
  SOURCE_PRETRAIN: './checkpoints/market_transformer_80.pth'
#  SOURCE_PRETRAIN: './checkpoints/market_resnet50_120.pth'

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('dukemtmc')
  ROOT_DIR: ('./data')
  SOURCE_NAMES: ('market1501')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 120
  BASE_LR: 0.008
  IMS_PER_BATCH: 64
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 120
  LOG_PERIOD: 40
  EVAL_PERIOD: 10
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
#  WEIGHT: './logs/sure_pseudo_label/duke_min4/transformer_120.pth'
#  WEIGHT: './logs/uda/uncertain_discard/Ablation_mse/m2d_lam03mse03/transformer_120.pth'
  WEIGHT: './logs/d_test/resnet_120.pth'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

#OUTPUT_DIR: './logs/uda/uncertain_discard/Ablation_mse/m2d_lam03mse03'
OUTPUT_DIR: './logs/d_test'


